const SUPABASE_URL = "https://yeizthxxuimyklcvilkw.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllaXp0aHh4dWlteWtsY3ZpbGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1MDEwOTQsImV4cCI6MjEwMjA3NzA5NH0.Uuu0nhM753phPwwLAgNtWHxas6wwxr7ZUaQhhOKFcpg";

const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
